### ISSUE TITLE
Docs still reference interfaces that don't exist in 2.0

### ISSUE THREAD

**Issue by nesl247** [SimpleBus/SymfonyBridge#11]
If you look at the event docs, or the upgrade docs, they still reference the interfaces such as `MessageHandler`.

**Comment by matthiasnoback** [comment]
That should not be the case - which exact URL are you looking at?

**Comment by nesl247** [comment]
These two file in particular.

https://github.com/SimpleBus/SymfonyBridge/blob/master/doc/upgrade_guide.md
https://github.com/SimpleBus/SymfonyBridge/blob/master/doc/event_bus_bundle.md

**Comment by matthiasnoback** [comment]
Ah, I see. The upgrade guide is a bit tricky, it is mainly about MessageBus itself. But this asks for an upgrade guide for 2.x to 4.0. The event bus examples can easily be modified to reflect the latest changes. If you can, please make a PR for that.

**Comment by nesl247** [comment]
I will have to do so after work, but I'll try and get it done today. Thanks for the quick feedback though!

**Comment by matthiasnoback** [comment]
Cool, no worries, thanks for reporting!

**Comment by matthiasnoback** [comment]
I fixed this by removing those old-style references and adding an upgrade guide for v4.0.
