### ISSUE TITLE
Unclear dependency on simple-bus/doctrine-orm-bridge

### ISSUE THREAD

**Issue by xphere** [SimpleBus/SymfonyBridge#12]
Steps to reproduce:

1. Install a [symfony standard distro](https://github.com/symfony/symfony-standard)
2. Follow steps from [symfony-bridge documentation](http://simplebus.github.io/SymfonyBridge/doc/getting_started.html)

    2.1. Run `composer require simple-bus/symfony-bridge`
    2.2. Add `new SimpleBus\SymfonyBridge\SimpleBusCommandBusBundle()` to `AppKernel`
    2.3. Add `new SimpleBus\SymfonyBridge\SimpleBusEventBusBundle()` to `AppKernel`
    2.4. Add `new SimpleBus\SymfonyBridge\DoctrineOrmBridgeBundle()` to `AppKernel`

3. Run `app/console cache:clear`

An error appears:
```
PHP Fatal error:  Class 'SimpleBus\DoctrineORMBridge\EventListener\CollectsEventsFromEntities' not found in app/cache/dev/appDevDebugProjectContainer.php
```

This can be fixed by calling `composer require simple-bus/doctrine-orm-bridge` after step 2.1.

I think this is related to the `simple-bus/doctrine-orm-bundle` being "suggested" as a dependency but not required. Either documentation should state that you need to add this dependency manually to start using `DoctrineOrmBridgeBundle` or the file `composer.json` should make this dependency a required one.

**Comment by ruudk** [comment]
Maybe an exception could help too?

If `SimpleBus\DoctrineORMBridge` not found, throw exception and say that the user probably forgot to install the ORM bridge?

**Comment by hacfi** [comment]
`simple-bus/doctrine-orm-bridge` is only a suggested package so you have to run
```
composer require simple-bus/doctrine-orm-bridge
```

**Comment by xphere** [comment]
@hacfi That's what I'm asking: if it should remain a suggestion dependency, then the documentation needs to make this explicit. But if it's a hard dependency [as I understand by this tweet](https://twitter.com/xphere/status/595901627804078080), then it's `composer.json` who needs to be fixed.

**Comment by ruudk** [comment]
Well `simple-bus/doctrine-orm-bridge` requires `doctrine/orm`. If we'd require this package by default it would require `doctrine/orm` too. So I guess the doc should be changed.

**Comment by matthiasnoback** [comment]
I'll add some lines to the docs soon :)
Op 11 mei 2015 11:18 schreef "Ruud Kamphuis" <notifications@github.com>:

**Comment by xphere** [comment]
Nice! The point made by @ruudk is key for this decision: Not every symfony project using `simple-bus` needs to depend on `doctrine/orm`. This solves my initial question at twitter. Thanks!

**Comment by matthiasnoback** [comment]
Right, also, maybe it's good to have that exception, warning users about
the extra dependency.
Op 12 mei 2015 19:07 schreef "Berny Cantos" <notifications@github.com>:

**Comment by matthiasnoback** [comment]
I added a note about the extra dependency you need to install: http://simplebus.github.io/SymfonyBridge/doc/doctrine_orm_bridge_bundle.html. Maybe if someone encounters this problem again, we can add an exception as well. Would you agree with that?

**Comment by kniziol** [comment]
@matthiasnoback, exception would be better solution IMHO, because it's not clear that ```simple-bus/doctrine-orm-bridge``` package should be installed too.
