### ISSUE TITLE
write operations in event listeners

### ISSUE THREAD

**Issue by dadamssg** [SimpleBus/SymfonyBridge#20]
I've become a little confused on how to create listeners that perform write operations. 

For example, I have a `RegisterUser` command which creates a `User` instance and adds it to my `UserRepository`. The `User`'s constructor raises a `UserRegistered` event. I have an event listener that looks like below. 

The problem arises when I send the `FindUserById` command.  The `$command->getUser()` returns a null. I'm assuming that's because of the `FinishesHandlingMessageBeforeHandlingNext` middleware. Because the `RegisterUser` command is still being processed, the `FindUserById` command get's put on a queue(I believe) and doesn't get executed right away. 

I could interact with my `UserRepository` directly in the listener but when I set a confirmation token and attempt to persist that `User`, the entity manager's `flush()` method will never be called, leaving the change un-persisted. Any ideas/tips?

```php
class SendConfirmationEmailListener
{
    /**
     * @var MessageBus
     */
    private $commandBus;

    /**
     * @var string
     */
    private $systemUserId;

    /**
     * @param MessageBus $commandBus
     * @param string $systemUserId
     */
    public function __construct(MessageBus $commandBus, $systemUserId)
    {
        $this->commandBus = $commandBus;
        $this->systemUserId = $systemUserId;
    }

    /**
     * @param UserRegistered $event
     */
    public function notify(UserRegistered $event)
    {
        $command = new FindUserById($this->systemUserId, $event->getUserId());
        $this->commandBus->handle($command);

        if (!$command->getUser()->isEnabled()) {
            $this->commandBus->handle(new AssignConfirmationToken($this->systemUserId, $event->getUserId()));
            $this->commandBus->handle(new SendConfirmationEmail($this->systemUserId, $event->getUserId()));
        }
    }
}
```

**Comment by matthiasnoback** [comment]
Good questions!

Well, SimpleBus, without being too explicit about it, encourages a true command/query segregation. This means that command handlers can't have return values and they can't be easily tricked into having them as well. Of course, if everything is being handled synchronously you can do what you're doing and set a return value on a command, even though in this case I'd say, having a FindUserById command isn't all that useful - you might as well just inject the repository and find the user yourself :) A command is supposed to change something in the application, while `FindUserById` is a query which shouldn't have any side-effects of course.

Also, yes, you are experiencing the effect of the `FinishesHandlingMessageBeforeHandlingNext` middleware, because a command isn't immediately handled. However, using the repository itself to find the user solves this problem right-away.

About transactions: each command will be handled in its own transaction. It's a good idea to dispatch new commands for everything that causes a new change.

**Comment by matthiasnoback** [comment]
I hope this helps, if not: just let me know!

**Comment by dadamssg** [comment]
It adds a new perspective. Thanks for the response!

I created the `FindUserById`, and other getter commands because I have Authorization(I know we don't agree on this :) ), statistics gathering, and command logging middleware. I like the idea of truly having a single point of entry into my application. I guess I need to read up on command/query segregation. 

How would you go about solving my dilemma of assigning a new confirmation token and sending an email on the `UserRegistered` event?

**Comment by matthiasnoback** [comment]
:)

Well, I may not understand this correctly, but if the  second, command is dependent on the first to be executed (I think it is), then you should dispatch the first command, and while handling that command, dispatch an event (like `ConfirmationTokenAssigned`), subscribe to it, and dispatch the second command (`SendConfirmationEmail`).

**Comment by dadamssg** [comment]
Hmm...I'm using the confirmation token for 2 things:

1. Confirming their account via link in an email. 
2. Resetting their password via link in an email. 

My listener could look like this but it seems really hacky. Maybe it's not, I don't know :/

```php
class ConfirmationTokenAssignedListener
{
	public function notify(ConfirmationTokenAssigned $event)
	{
		$user = $this->users->findById($event->getUserId());

		if ($user->isEnabled()) {
			$this->mailer->sendPasswordResetEmail($user);
		} else {
			$this->mailer->sendAccountConfirmationEmail($user);
		}
	}
}
```
I could create two separate tokens and fire different events when they change but that seems a little overkill but my be what I need if I want that explicitness. Thoughts?

**Comment by dadamssg** [comment]
Come to think of it. I could decorate my `UserRepository` to fire events. I think this will work nicely. 

```php
class User
{
	public function __construct(UserId $id, Email $email)
	{
		$this->id = (string)$id;
		$this->email = $email;

		$this->record(new UserRegistered($this->id));
	}

	public function isNew()
	{
		foreach ($this->recordedMessages() as $event) {
			if ($event instanceof UserRegistered) {
				return true;
			}
		}

		return false;
	}
}
```
```php
class EventfulUserRepository implements EventfulUserRepository
{
	public function add(User $user)
	{
		if ($user->isNew()) {
			$this->eventBus->handle(new UserRegistering($user->getId()));
		}

		$this->users->add($user);
	}
}
```

I can have a listener subscribed to two these new events. 

```php
class AccountConfirmationListener
{
	public function assignToken(UserRegistering $event)
	{
		$user = $this->users->findById($event->getUserId());

		if (!$user->isEnabled()) {
			$user->setConfirmationToken(new ConfirmationToken());
		}
	}

	public function sendEmail(UserRegistered $event)
	{
		$user = $this->users->findById($event->getUserId());

		if (!$user->isEnabled() && $user->getConfirmationToken()) {
			$this->mailer->sendAccountConfirmationEmail($user);
		}
	}
}
```

**Comment by dadamssg** [comment]
well crap. that won't work with doctrine since the `$user` isn't in doctrine's identity map. No user will be found in the `assignToken()` method. Dangit.

**Comment by matthiasnoback** [comment]
@dadamssg Did you manage to find a solution for this? Maybe I'm repeating myself, but the flow is:

start transaction - handle command - commit transaction - process events

If you want to dispatch events in other places, you shouldn't do it be directly calling the event bus, instead, record the event (like described here: http://simplebus.github.io/MessageBus/doc/message_recorder.html and here: http://simplebus.github.io/SymfonyBridge/doc/event_bus_bundle.html).

**Comment by dadamssg** [comment]
Right, I understand all of this. I think I've come to a solution. First, let me layout a scenario. 

A user registers. This raises a `UserRegistered` event. A `ConfirmationEmailListener` picks that up and sends an email. The email doesn't get sent in the `RegisterUserHandler` directly because the user entity hasn't been committed by the transaction. It also makes sense because sending an email is a side affect of storing the user. It's not the primary action in this case. 

That's all fine and good but what happens if the email didn't get sent or it went into the user's spam folder? A `ResendConfirmationEmail` command seems reasonable...except the handler will look strange and broken to someone new to the system. 

```php
class ResendConfirmationEmailHandler
{
    /**
     * @var UserRepository
     */
    private $users;
 
    /**
     * @param UserRepository $users
     */
    public function __construct(UserRepository $users)
    {
        $this->users = $users;
    }  

    public function handle(ResendConfirmationEmail $command)
    {
        $user = $this->users->findById($command->getUserId());

        $user->setConfirmationToken(new ConfirmationToken());

        $this->users->add($user);
    }
}
```

The mailer isn't being used in the handler because we cannot be sure that the new confirmation token was successfully committed to the database. Our `DoctrineUserRepository::add()` method doesn't call `$this->getEntityManager()->flush()`. Soooo our `ResendConfirmationEmailHandler` doesn't actually send an email? Wtf? The programmer has to be aware that setting a new token will raise a `ConfirmationTokenChange` event that will get dispatched later and that a listener will pick that up and actually do the sending. That feels wrong to me. 

To me, the solution is to have better, more explicit, control over transactions. That means calling `flush()` myself and not using the the `WrapsMessageHandlingInTrasaction` middleware. That way my command handler can look more reasonable. 

```php
class ResendConfirmationEmailHandler
{
    //

    public function handle(ResendConfirmationEmail $command)
    {
        $user = $this->users->findById($command->getUserId());

        $user->setConfirmationToken(new ConfirmationToken());

        $this->users->add($user);

        $this->mailer->sendAccountConfirmationEmail($user);
    }
}
```

Because I'm not calling `flush()` in my `add()` method, I can be sure the change has been persisted. 

So what about commands that need to be wrapped in a transaction? I have two options:

1. Create a middleware for this:

```php
class WrapsSuitableCommandsInTrasaction
{
    public function handle($command, callable $next)
    {
        if ($command instanceof RequiresTransaction) {
            $this->wrapInTransaction($command, $next);
            return;
        }    

        $next($command);
    }

    private function wrapInTransaction($command, callable $next)
    {
        $em = $this->registry->getManager($this->emName);

        try {
            $em->transactional(function () use ($command, $next) {
                $next($command);
            });
        } catch (\Exception $e) {
            $this->registry->resetManager($this->emName);
            throw $e;
        }
    }
}
``` 

2. Control the transaction explicitly within the handler:

```php
class RequestPasswordResetHandler
{

    public function __construct(UserRepository $users, TransactionManager $tx, UserMailer $mailer)
    {
        //
    }

    public function handle(RequestPasswordReset $command)
    {
        $user = $this->users->findById($command->getUserId());

        $user->setConfirmationToken(new ConfirmationToken());

        $this->persistUser($user);

        $this->mailer->sendPasswordResetInstructions($user);
    }

    private persistUser(User $user)
    {
        $this->tx->begin();
        
        try {
            $this->users->add($user);
            $this->tx->commit();
        } catch (\Exception $e) {
            $this->tx->abort();
            throw $e;
        }  
    }
}
```

I understand I'll be missing out on doctrine's more efficient way of persisting data when multiple entities get ~persist()`ed and then `flush()`ed but I think I'm will to take that trade off for the more explicit handlers.

**Comment by dadamssg** [comment]
[Here's my first draft of creating the compiler pass](https://gist.github.com/dadamssg/e1bea7329e8bf93c8b04).

**Comment by matthiasnoback** [comment]
I've been reading your code again and I think you're heading in the wrong direction here. Some comments:
- the actual database transaction is an infrastructural concern, which you shouldn't be worried about inside the command handler itself.
- using the token for two different things is confusing (but I guess you realized this as well ;)).
- sending the email in the event listener if it's the core "task" isn't the right thing to do (but I think you agree with that as well!).
- I think the problem lies with modifying the User entity and setting a confirmation token on it. I think it's better to invert the relation here: the RequestPasswordReset command handler creates a new PasswordResetRequest entity, which naturally contains the token and the user id. Now the event, PasswordResetRequested actually triggers the email to be sent.

**Comment by matthiasnoback** [comment]
I hope this helps!

**Comment by dadamssg** [comment]
@matthiasnoback that is an interesting take on the problem, your last point. I'll have to think about that. Thanks!

**Comment by matthiasnoback** [comment]
You're welcome! And thanks for sharing!
