### ISSUE TITLE
Typo in Upgrade Guide

### ISSUE THREAD

**Issue by josecelano** [SimpleBus/SymfonyBridge#3]
In this docs page:

https://github.com/SimpleBus/SymfonyBridge/blob/master/doc/upgrade_guide.md

This is a sample event subscriber service:

´´´´
services:
    bar_event_subscriber:
        class: Fully\Qualified\Class\Name\Of\BarEventSubscriber
        tags:
            - { name: event_subscriber, handles: Fully\Qualified\Class\Name\Of\BarEvent }
´´´´
I think "handles" must be replaced with "subscribes_to"

**Comment by matthiasnoback** [comment]
Fixed, thanks for reporting!
