### ISSUE TITLE
Command bus as lazy service?

### ISSUE THREAD

**Issue by portey** [SimpleBus/SymfonyBridge#44]
Hi, 

Using this bundle with rabbitMQ bridge. When symfony container initialize "command_bus" service, new connection to rabbitMQ is initialized. And it can decrease performance when command bus was not used, for example if validation not passed. 

Is it possible to mark command_bus as lazy service not using compiler pass?

**Comment by cmodijk** [comment]
We can look into this but the RabbitMQ connection can also be marked as lazy;

```
old_sound_rabbit_mq:
    connections:
        default:
            host:                   %rabbitmq_host%
            port:                   %rabbitmq_port%
            vhost:                  %rabbitmq_vhost%
            user:                   %rabbitmq_user%
            password:               %rabbitmq_password%
            lazy:                   true
            keepalive:              true
```

**Comment by cmodijk** [comment]
@portey At this time i don't see any reason to keep this open. If you still feel the need for this please reopen this item.
