### ISSUE TITLE
Setup/Documentation headache

### ISSUE THREAD

**Issue by samvdb** [SimpleBus/SymfonyBridge#54]
For a bundle with the name "simplebus" its setup is far from simple.

Having to navigate through 5 different sites of documentation, jumping back to the github repo to find the documentation link each time is a pain.
It also lacks a "general" overview of what steps are required to setup all the different components.

Wouldn't it be better to merge all the documentation together on 1 site?

/edit: Just noticed an issue here with the link to the new documentation. Guess this can be closed.

**Comment by cmodijk** [comment]
Hi @samvdb thanks for taking the time to open this issues. We are aware of this and we are working on it but it is taking some time to complete;
* https://github.com/SimpleBus/docs
