### ISSUE TITLE
AutoWire based on interface

### ISSUE THREAD

**Issue by cmodijk** [SimpleBus/SymfonyBridge#59]
After looking into the Symfony AutoWire a little more i found the `registerForAutoconfiguration` method on the container. The question here is should we add a interface for the handlers with the `registerForAutoconfiguration` to not even need the configuration? 

@ruudk What do you think? 

* https://medium.com/@rubenknol/symfony-3-3-dependency-injection-autoconfigure-3rd-party-bundles-10534071254
* http://symfony.com/blog/new-in-symfony-3-3-service-autoconfiguration

**Comment by ruudk** [comment]
I think the beauty of SimpleBus is that the Commands, Events, Handlers and Subscribers don't need to inherit or implement anything from SimpleBus.

**Comment by cmodijk** [comment]
That's true but i'm not saying that we should recommend it but we could add support for it

**Comment by garak** [comment]
So you prefer to add an interface to all your handlers instead of writing 5 lines of configuration?

**Comment by cmodijk** [comment]
@garak Hmm prefer if s big word in some projects i use interfaces to 'tag' things yes but the reason why i asked is that i was working with symfony security voter and after i created the class it works out of the box as i already need to implement a interface that felt nice.

**Comment by garak** [comment]
But the VoterInterface is needed for different reason (ensure that class implement methods).
Here there's no need to implement any method, so adding an Interface for something that's not interface-related is wrong.

**Comment by caciobanu** [comment]
I think that an interface introduced now for simplicity would make it harder to get rid of it later if that is decided.
