### ISSUE TITLE
Tags for symfony 4 support

### ISSUE THREAD

**Issue by caciobanu** [SimpleBus/SymfonyBridge#64]
Hi guys,

After https://github.com/SimpleBus/JMSSerializerBundleBridge/pull/13 is merged, is it possible to get a tag for the following repo's to get the Symfony 4 support usable with composer without requiring dev-master?
- https://github.com/SimpleBus/SymfonyBridge
- https://github.com/SimpleBus/JMSSerializerBundleBridge

Thanks,
Catalin

**Comment by ruudk** [comment]
Tagged https://github.com/SimpleBus/SymfonyBridge/releases/tag/v5.1.2

**Comment by ruudk** [comment]
Tagged https://github.com/SimpleBus/JMSSerializerBundleBridge/releases/tag/v3.0.1

**Comment by caciobanu** [comment]
Great! Thanks allot guys!
