### ISSUE TITLE
Add Symfony flex recipe 

### ISSUE THREAD

**Issue by cmodijk** [SimpleBus/SymfonyBridge#65]
We should look into making a Symfony flex recipe (one or more) to allow easy install using Symfony flex.

**Comment by garak** [comment]
I don't see any specific reason for a recipe.
If you just require this bundle using flex, the basic configuration is enough

**Comment by cmodijk** [comment]
To be honest i have not tried flex yet i created this to get some feedback on if we should and why thanks for your response 👍

**Comment by caciobanu** [comment]
I don't think that recipes for the Symfony bundles offered by SimpleBus would make sense because all the features are enabled by default, except logging.

**Comment by cmodijk** [comment]
I'm closing this as stated by @caciobanu we don't need a recipe if we see a need we can create a pull request.
