### ISSUE TITLE
Web debug toolbar integration

### ISSUE THREAD

**Issue by magnusnordlander** [SimpleBus/SymfonyBridge#7]
Hi,

I'd like to see some web debug toolbar integration. Is this something that's on your roadmap for the project, @matthiasnoback? If so, would you like me to work on it and send you a PR?

**Comment by matthiasnoback** [comment]
That would be very nice indeed!

I had been thinking previously about a middleware that collects every message for any message bus in memory. For this you would need a list of message buses and the data collector stuff for the profiler (and of course some view stuff for the toolbar).

For other parts of SimpleBus I already need a way to discover which message buses are in use (`command_bus`, `event_bus`, `asynchronous_command_bus`, etc.), so I will soon add the tag `message_bus` to existing message bus services. This way you could iterate over them and register that data collector middleware I was talking about.

It would be absolute great if you could work on this, thanks for offering your help and looking forward to the results :)

**Comment by magnusnordlander** [comment]
Okay, so, I spent some time on this. I'm not done, but if you have the time, I'd like for you to take a look, and just confirm that this is the direction you want me to be heading in.

https://github.com/fervo/SymfonyBridge/tree/profiler

So some notes:

* A lot of the functionality isn't really specific to Symfony, so it probably should be extracted into some kind of a message logging package.
* As you said, a tag for message buses would be necessary to discover other buses than event_bus and command_bus.
* I'm going to be adding an interface for messages to be able to add extra data to the view
* I'm also planning to switch message IDs to a regular counting number

**Comment by matthiasnoback** [comment]
Excellent work! I will just add some comments to the code :)

**Comment by matthiasnoback** [comment]
It seems that adding comments to random code parts is impossible ;)

- I don't think it's possible to rely on the priorities of middlewares and conclude that a command has been fully handled, etc. Given that the command bus "promises" to handle a command *or* throw an exception, we should only log incoming messages and assume successful handling. We might however do something like this inside the middleware:

```php
$this->logIncomingMessage($message);
try {
    $next($message);
} catch (\Exception $exception) {
    $this->logFailure($message, $exception);
    throw $exception;
}
```
- The actual `Message` object can change between middlewares (because of the `$next($message)` call). We can't assume that the handled message is the same object as the incoming message, so we can't rely on `spl_object_hash()` for generating an ID. However, given my previous command, I don't know if we still need an ID.
- The `messageClass` key in the data collector should just contain the class I think. Or instead of hard-coding the name-resolving you could inject the actual instance of `MessageHandlerResolver` used by the bus itself. However, these can be different for each message bus, so I'd say: keep it simple with just the class name.

**Comment by matthiasnoback** [comment]
Another feature that might be interesting at some point would be a list of registered middlewares (to debug any configuration issues).

**Comment by matthiasnoback** [comment]
Also - you're right about the logging stuff belonging to a separate package. And as I understand it, Silex also supports the profiler and the debug bar, so we should separate this from the SymfonyBridge and just require it as a dependency (since I think it should be available by default). Shall I create a new project as part of the SimpleBus organization for this project?

Finally, I think that whether or not this feature is enabled/loaded should be dependent on the Symfony configuration (whether or not the profiler is enabled/we are in debug mode/etc.).

**Comment by matthiasnoback** [comment]
Thanks again and looking forward to what lies ahead!

**Comment by magnusnordlander** [comment]
> I don't think it's possible to rely on the priorities of middlewares and conclude that a command has been fully handled, etc. Given that the command bus "promises" to handle a command or throw an exception, we should only log incoming messages and assume successful handling.

You're probably right. We can however do better than only logging incoming messages, if we want to. We could decorate each middleware with a logging decorator, and thus be able to trace each message as it passes through the middlewares. That would also keep the possibility of tracking the messages using ids.

> The messageClass key in the data collector should just contain the class I think. Or instead of hard-coding the name-resolving you could inject the actual instance of MessageHandlerResolver used by the bus itself. However, these can be different for each message bus, so I'd say: keep it simple with just the class name.

Will do

> Another feature that might be interesting at some point would be a list of registered middlewares (to debug any configuration issues).

Agreed

> Also - you're right about the logging stuff belonging to a separate package. And as I understand it, Silex also supports the profiler and the debug bar, so we should separate this from the SymfonyBridge and just require it as a dependency (since I think it should be available by default). Shall I create a new project as part of the SimpleBus organization for this project?

Actually, I think two new projects are in order. One for the logging portions of this, and one for the WebProfiler integration. It would be completely plausible to use the same middlewares to log to e.g. a PSR-4 logger.

> Finally, I think that whether or not this feature is enabled/loaded should be dependent on the Symfony configuration (whether or not the profiler is enabled/we are in debug mode/etc.).

Indeed, this is definitely planned before I submit a PR :)

**Comment by matthiasnoback** [comment]
Hi @magnusnordlander! How are you doing? Did you find any time to work on this project? Do you need something from me?

**Comment by magnusnordlander** [comment]
I've been busy the last few weeks, but I did find some time this past tuesday, which at least allowed me to regroup following the upstream changes going on. I do have a couple of things I'd like to discuss with you.

1. SymfonyBridge consists of multiple bundles depending on whether you want a command bus or an event bus (or both). There's also the possibility of a user adding their own buses. By using the message_bus tag I can discover tagged buses, but this means that both bundles would be relying on some shared services.

I guess the question is, do you want a single SimpleBus profiler pane (which would contain all buses), or separate profiler panes for the Command Bus and the Event Bus (which would not contain custom buses)? If the former, how do you want me to handle the shared services? Should profiling be a separate bundle, or just a DI extension that gets loaded by either bundle?

2. I'm using the PSR-4 logging support in the library to log the messages for profiling. Would you consider it important for the bridge to support profiling and logging to monolog simultaneously?

**Comment by matthiasnoback** [comment]
> SymfonyBridge consists of multiple bundles depending on whether you want a command bus or an event bus (or both). There's also the possibility of a user adding their own buses. By using the message_bus tag I can discover tagged buses, but this means that both bundles would be relying on some shared services.
I'm actually a bit sad about my previous decision to do it like this. It started as an experiment but now (I guess) it's harder to use something like an automatic git subtree splitting tool that would allow me to develop everything in one repository...

> I guess the question is, do you want a single SimpleBus profiler pane (which would contain all buses), or separate profiler panes for the Command Bus and the Event Bus (which would not contain custom buses)? If the former, how do you want me to handle the shared services? Should profiling be a separate bundle, or just a DI extension that gets loaded by either bundle?
In the future I'd like to assume that everybody uses both command and event bus, so I'd say: everything in one pane.

> I'm using the PSR-4 logging support in the library to log the messages for profiling. Would you consider it important for the bridge to support profiling and logging to monolog simultaneously?
I didn't see the logging part anywhere in the code.  I'd say all the details don't need to be in the log file as well. Besides, `SimpleBus/MessageBus` already contains some rudimentary PSR-compliant logging facilities.

Finally, what about taking some shotcuts to get a minimum viable version of this project out soon? For me the minimum would be:
1. A list of all messages that have been passed through to any service tagged as `message_bus` (so this could be solved using a middleware).
2. A list of all message buses and their middlewares in the actual order in which they have been set up.
What are your thoughts?

**Comment by matthiasnoback** [comment]
Oh and another shortcut that we should take is to not make this Silex-ready yet. We can always, on demand, move some shared code out of the SymfonyBridge.

**Comment by magnusnordlander** [comment]
I've updated my branch with a working version having the requirements above. (https://github.com/fervo/SymfonyBridge/tree/profiler)

It DOES require a change in MessageBus, specifically MessageBusSupportingMiddleware, which I have not pushed because I want your input. I need a way to get all the middlewares from a given MessageBus. In my local copy I added a simple getMiddlewares method like this:

```php
    /**
     * Returns a list of middlewares. Should only be used for introspection.
     *
     * @private
     * @return array<MessageBusMiddleware>
     */
    public function getMiddlewares()
    {
        return $this->middlewares;
    }
```

If this is fine, then I can just submit a PR for it (or you could add it, it's the same to me). However, if you do not want to expose those internals to anyone and everyone, I could also create a subclass, IntrospectableMessageBusSupportingMiddleware or something like it, but that would require making ```$this->middlewares``` protected instead of private. I COULD also use reflection, but I decided against that.

Which do you prefer?

**Comment by matthiasnoback** [comment]
That's great! Yes, if you want, please provide a PR for the local solution
you have.
Op 12 apr. 2015 20:13 schreef "Magnus Nordlander" <notifications@github.com

**Comment by garak** [comment]
Any news on this?

**Comment by cmodijk** [comment]
@garak To be honest this is a very old suggestion and we never got to a pull request. I'm not sure if the integration that @magnusnordlander did stil works with the latest versions of `MessageBus` and `Symfony`.

**Comment by rvanlaak** [comment]
... the `profiler` changed in the meanwhile, so no that won't be compatible. I do think that the `dataCollector` on that branch might still be valid though.

So, anyone willing to help to make this feature mergeable?

**Comment by garak** [comment]
Since #57 has been merged, I guess that this issue can be closed.

**Comment by cmodijk** [comment]
Closed, but i disabled it in the Mono Repository https://github.com/SimpleBus/SimpleBus/issues/21
