### ISSUE TITLE
Bug: MessageBusDataCollector contains 1 abstract method

### ISSUE THREAD

**Issue by MvanRietschoten** [SimpleBus/SymfonyBridge#72]
Hello kind sir,

After installing this bundle I get the following error message while it runs cache:clear.

```
PHP Fatal error:  Class SimpleBus\SymfonyBridge\DataCollector\MessageBusDataCollector contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface::reset) in /var/www/dev.arovo.nl/vendor/simple-bus/symfony-bridge/src/DataCollector/MessageBusDataCollector.php on line 74
!!  
!!  In MessageBusDataCollector.php line 74:
!!                                                                                 
!!    Error: Class SimpleBus\SymfonyBridge\DataCollector\MessageBusDataCollector   
!!    contains 1 abstract method and must therefore be declared abstract or imple  
!!    ment the remaining methods (Symfony\Component\HttpKernel\DataCollector\Data  
!!    CollectorInterface::reset) 
```

I use dev-master of this bundle, currently at: 88056e9052859ae6e7b2162aa620b0c5b251fe68
The httpkernel with the DataCollectorInterface where the reset method is in 4.0.x-dev: 6b684698aa42c46aebfe960118d5cf40fea8461a

It looks the same as this one: https://github.com/symfony/symfony/issues/25215
Hope I'm helping, haven't found a solution yet. Other then hoping this method will be implemented.

**Comment by cmodijk** [comment]
Hi, Thank you for opening this issue 👍 

1. Please open issues on our mono repository this issue tracker is going to be closed in a few days
2. Never use dev-master in this case it is a know issue and work in progress 
https://github.com/SimpleBus/SimpleBus/pull/30

**Comment by MvanRietschoten** [comment]
Thanks for the fast reply!

I used a symfony contrib recipe for msgphp/user-bundle which uses this in require-dev. 
I normally don't use master indeed :)

Setting this to ^v5.1 did the trick :)

**Comment by cmodijk** [comment]
@MvanRietschoten Great! Thanks for checking it. Maybe create a pr to fix the symfony contrib recipe for msgphp/user-bundle?
